### ISSUE TITLE
The fixed header stays after navigating away in angular

### ISSUE THREAD

**Issue by Worthy7** [DataTables/DataTables#1001]
Angular doesn't actually reload the page, so the problem is that whatever is enabling the fixed header, is not being disabled after the page is left.
So if I go to another page (with no DT) and scroll down, the header suddenly appears at the top of the page.

**Comment by DataTables** [comment]
Are you calling the `destroy()` method?

In future, could you post support questions in the [forums](//datatables.net/forums) so there is a single searchable source for DataTables support? Thanks.

**Comment by Worthy7** [comment]
It's an issue, so I thought that GitHub would be the place to write it.... What do you want to use github issue for then? 
I did use a workaround to get it working, but if this could be somehow incorporated into automatically as part of core DT, then that would be great.

**Comment by DataTables** [comment]
I'm still not clear that there is a bug in DataTables here. It doesn't directly have any Angular integration in the core. If you expect a click away to destroy the table, that would be a task for whatever Angular integration you are using for DataTables.

In terms of github issues - I'd rather they weren't used at all to be honest. The forum should be the main stop. I'd put the github issues into readonly mode if I could, but I don't believe that's an option in github. I don't want to disable them completely, since that would hide them and there is some useful information here.

**Comment by Worthy7** [comment]
OK fair enough, perhaps you should change the default issue template so it says to simply not post here.
I guess it is an angular problem and not a datatables problem. But I'm sure a simply "on page unload" could be added no? :)
