### ISSUE TITLE
minified version in npm

### ISSUE THREAD

**Issue by denkuz08** [DataTables/DataTables#1018]
Hi. How can i install datatables from npm with minified file? When i try 

`npm install datatables.net --save`

it contains only non-minified source file.

![image](https://user-images.githubusercontent.com/15865994/35980166-15aa31ea-0cfb-11e8-8fc6-213182b2ae07.png)

**Comment by DataTables** [comment]
The 1.10.16 release didn't include the minified version I'm afraid. That has been fixed in dev and will be resolved with the 1.10.17 (not sure when that will be, not that long now). For now you would need to run it through a local minifier.

In future, could you post support requests in the forums as the new issue template requests.
