### ISSUE TITLE
When using .data to update, then .remove to remove a row, id selector can return stale data, or fails

### ISSUE THREAD

**Issue by ioev** [DataTables/DataTables#1023]
http://jsfiddle.net/h5uw1oL6/4/

This only seems to happen with this particular chain of events, update a row using the .data() api call, then .remove() it.  After this, using the id returns the wrong row (seems to be the following one) or sometimes will return a collection with a length of 1, but will raise an exception if .node() is called on it.

Edit:  I just realized that this is actually because of how I'm updating the row, using an array.  Seems there's an internal field of some sort (DT_RowId) that makes up part of the data, and if that's not passed in, it seems to get cleared out internally by the call to .data().  Would it make sense to have the id only update if the DT_RowId key exists?

**Comment by DataTables** [comment]
This is a good one - thanks! You are correct, its due to the data update. I've made a change locally that will insert the id into the array if you update the row with a plain array, just as it does when the row is original read, which addresses this.

I'll commit it shortly when I've written a test case.

**Comment by DataTables** [comment]
[Fixed here](https://github.com/DataTables/DataTablesSrc/commit/2f6d2fec6416b6e1fc47d1050c9ed240eb820588).

Thanks again
