### ISSUE TITLE
Bug with multi-column sort with both numeric AND alphabetic sort

### ISSUE THREAD

**Issue by prasoc** [DataTables/DataTables#1027]
I have found an issue with multi-column sorting. You can only sort by one "type" (such as numeric columns OR alphabetic columns, but not both!). Even in the multi-sort example [here]

(https://datatables.net/examples/basic_init/multi_col_sort.html) on the official DT website shows this error:

![image](https://user-images.githubusercontent.com/9812458/36602596-4a296862-18b0-11e8-80c3-ccd14cb2fd48.png)

then sorting by any other column does nothing:

![image](https://user-images.githubusercontent.com/9812458/36602623-60650762-18b0-11e8-81e1-189dc4e286ee.png)

Thanks
James

**Comment by prasoc** [comment]
actually I think it's a little more nuanced than "one column type only". If you have multiple numeric columns, for some reason ONE of them breaks; I think it's the first column index that suffers from it

**Comment by DataTables** [comment]
The screenshots above are correct - the salary column is sorted first and if there needs to be a tie breaker it would sort on the office column. Since the salary column contains only unique values there is no need to refer to another column for a secondary sort.

If you sort first by the office column and then add the salary column you will see it multi-column sort since the office column does not contain only unique values.

**Comment by prasoc** [comment]
Of course. To me, it just seemed strange that you can sort by one column (the office) and then sort by salary, but not the other way around. Feel a little stupid now! This also solves the problem with my application, too.
