### ISSUE TITLE
Custom filter and rendering causes incorrect row data to be returned

### ISSUE THREAD

**Issue by smasala** [DataTables/DataTables#1034]
Version: 1.10.16

If you set a custom renderer:

```
column: [{
    title: 'myTitle',
    render: function(data, type, rowData, meta) {
        return data.someObjectProperty;
    }
}]
```

Then you create a custom filter by using the `$.fn.dataTable.ext.search` "workaround".

```
var dt = $('#example').DataTable(...);
$.fn.dataTable.ext.search.push(function (api, rowData, rowIndex) {
    // rowData for column "myTitle" is the rendered output not the object
   // to get the real data:
   dt.rows(rowIndex).data()[0][columnIndex]
   // general question: why doesn't param api have "rows()"?
});
```

Then `rowData` is the rendered output and not the original data output.

**Comment by DataTables** [comment]
Actually, to get the original data object for the row, use the [fourth parameter](https://datatables.net/manual/plug-ins/search) that is passed into the search function.

The "api" parameter (as named there) isn't actually an API instance, its a settings object, hence why you can't access a rows method on it. You could use `new $.fn.dataTable.Api( settings )` (as it should be correctly named. Its a settings object rather than an API instance for legacy reasons.

**Comment by smasala** [comment]
my bad didn't see that. Thanks though for the quick help!
