### ISSUE TITLE
When I set `order: false` and then click a heading I get a JS error

### ISSUE THREAD

**Issue by scottchiefbaker** [DataTables/DataTables#1038]
I have a table that I've disabled sorting via `order: false`. When I click on one of the column headers as if were trying to sort it, I get a Javascript error:

```
can't assign to property "length" on false: not an object
```

I would expect DataTables to fail silently, and not throw an error. 

I've created a very simple [test case](https://www.perturb.org/code/data-table-sort-bug.html) that show the bug in action.

**Comment by scottchiefbaker** [comment]
It's worth noting that if I use the [minified](https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js) version of the JS the error message changes to:

```
TypeError: e.push is not a function
```

**Comment by DataTables** [comment]
I'm getting a DNS error from the link to the test case: ERR_NAME_NOT_RESOLVED . Could you put it in JSFiddle or similar?

In future, could you post support requests in the [DataTables forums](//datatables.net/forums) as requested in the new issue text. Thanks.

**Comment by scottchiefbaker** [comment]
I've moved the code to JSFiddle [here](https://jsfiddle.net/qgo37ak1/). This is not a support request, everything is working. There is a JavaScript bug that's emitting an error in the console.

**Comment by DataTables** [comment]
Ah! I see. Thanks for the test case.

The `order` property can't be set to `false`. As [the reference document notes it should be an array](https://datatables.net/reference/option/order).

If you want to disable ordering in the table, [use the `ordering` property](https://datatables.net/reference/option/ordering).

The documentation doesn't list a boolean value as valid for the `order` property so I'm afraid I don't consider this to be a bug. It is undefined behaviour due to an incorrect configuration.

**Comment by scottchiefbaker** [comment]
You're 100% right! I don't know how I missed that. My apologies. Thank you for the prompt response.

**Comment by DataTables** [comment]
No worries! The names are _very_ similar.
