### ISSUE TITLE
TableTools plugin is not compatible with Row grouping

### ISSUE THREAD

**Issue by hszcg** [DataTables/DataTables#283]
I found the **TableTools** plugin is not compatible with **Row grouping**. I've tried to combine the following two examples together, and this is no action after i clicked the any button (csv/xls/pdf)... And this is no explicit error message found.

I suppose it could be caused by column spanning or whatever...

Would you please take a look on this?

TableTools
https://next.datatables.net/release-datatables/extensions/TableTools/examples/simple.html

Row grouping https://next.datatables.net/examples/advanced_init/row_grouping.html

**Comment by edgargonzalez17** [comment]
Hi, what is the status of this? i'm grouping my table but it doesn't group when i export to PDF.

**Comment by DataTables** [comment]
The status is probably won't fix thinking about it again now. The reason being is that TableTools for the export loops over the data contained within the DataTable, but the row grouping is injected after the fact.

I think until DataTables supports true grouping, which I'm afraid is quite a while away as there are a number of other features I need to create before it, then this can't be implemented here. As such, I'm going to close this issue since it isn't a feature that can currently be implemented.
