### ISSUE TITLE
Issue with datatables fixed columns in IE9 and firefox

### ISSUE THREAD

**Issue by Bostafly** [DataTables/DataTables#476]
I try to explain this issue : add a fixed columns works fine in chrome and IE10 +. But in IE9 and firefox, I found that the column doesn't extend correctly  in all the tables vertically. 

After some research, I found an issue in the calculation of the scrollbar. The size of the scroll bar who is calculate in jquery.datatables.js is not correct in IE9 but i don't know why...   In fact,  by replacing in  the function _fnScrollBarWidth the line
- Var w2 = inner.offsetWidth;
by
- var W2 = outer[0].offsetWidth;
the issue seems to be resolved.

 I wanted to know if it was a known issue who can be fixed for those wishing to use the fixed columns on some browsers.
Thanks

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please?

**Comment by Bostafly** [comment]
Ok : http://jsfiddle.net/mhvae4ab/7/. 
In IE9, at the bottom of the fixed columns ( the right columns : "Assurance"), we can see a gap ( a few pixel high). So the border and the last cell in the bottom of the fixed columns are not align.

**Comment by DataTables** [comment]
Great thanks. I'll try to take a look as soon as I can.

**Comment by DataTables** [comment]
Sorry for the delay. I've just [committed the fix](https://github.com/DataTables/DataTablesSrc/commit/57aa4b04ad56447f) and it will be in 1.10.6.

The problem was that IE9 wasn't expanding the width of the inner element under the scrollbar with width:100% (which sort of makes sense to me actually...). I've rewritten it to perform faster now :-)

Thanks for flagging this up!

**Comment by Cedoriku** [comment]
Hello,
I don't have time to upload a set exemple for demonstration, but after reading this thread, and this one https://github.com/DataTables/FixedColumns/issues/7, I updated my version of datatable (1.10.6) in order to fix my issues with FixedColumns on IE and Firefox, but the problem remains.

The thead th elements don't have the same width than the td elements below, so borders are offset.

For firefox, I used this (dirty) hack, which work:

@-moz-document url-prefix()
{
    table.dataTable thead > tr > th.caseChelou{
        padding-left: 18px;
        padding-right: 18px;
    }
    table.dataTable thead > tr > th.caseChelou.actionCell{
        padding-left: 18px;
        padding-right: 19px;
    }
    table.dataTable thead > tr > th.fixCaseChelou{
        padding-left: 16px;
        padding-right: 15px;
    }
    
}

.caseChelou is on the first th, .caseChelou.actionCell aims the second one, and .fixCaseChelou is the third..


On IE (with <![for IE]-- comment trick on css include), this hack fixes the display of the th's borders, but then an horizontal scroll-bar appears at the bottom of the block ("fixed"), which I've been unable to make disappear..:

table.dataTable thead > tr > th.caseChelou{
    /*
    padding-left: 19px;
    padding-right: 18px;
    */
}
table.dataTable thead > tr > th.fixCaseChelou{
    /*
    padding-left: 13px;
    padding-right: 14px;
    */
}

I gave up on that last one...

**Comment by DataTables** [comment]
I'm afraid that without an example showing the issue there isn't much I can do to help. But thanks for posting your workaround for Firefox.

**Comment by Cedoriku** [comment]
Thank You for the good huge work.
I was just notifying you that some issues seem to remain with different
browsers and FixedColumns.

If I ever have time to prepare an example set for JSFiddle, I'll let you
know.

Thank you

2015-04-21 17:30 GMT+02:00 Allan Jardine <notifications@github.com>:

> I'm afraid that without an example showing the issue there isn't much I
> can do to help. But thanks for posting your workaround for Firefox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataTables/DataTables/issues/476#issuecomment-94839543>
> .
>



-- 
<http://cedricchounavelle.free.fr>

**Comment by barryss** [comment]
Hi,
I'm using datatables 1.10.9 (tested with 1.10.11) with FixedColumns 3.2.1 and also got into this issue.
There is a horizontal scrollbar appearing at the bottom of fixed column(s) in Firefox and IE10.
In Chrome there is no issue.
I have a test example showing problem:
[http://bonin.tsb-it.pl/index.php/com-katalogziemniakow-katalogziemniakowszkodnikidanes-option-name/sor](url)

There are first 3 colums fixed. 0, 1 are hidden. 2 is the visible one with additional scrollbar at her bottom.
I can provide any additional info.
Thanks

**Comment by DataTables** [comment]
@barryss - Sorry for the delay in getting back to you about this! In your example you have 

```css
table.dataTable {
    border-collapse: collapse !important;
}
```

Could you change that to be `separate` please? The problem with `collapse` is that it makes the column width calculations absolutely impossible to match across the scrolling table since the actual width of the cells then depends upon the content of the table (and of course the header and body tables have different content). DataTables will measure the cells and set their widths as required to try and match the alignment up, but with scrolling enabled (which splits the table into two components parts) the alignment is simply impossible to do.

**Comment by dskumarxd** [comment]
Hi,
I'm using jquery.datables version 1.10.12,my code is working perfect with chrome and IE, But not working with firefox. In console it gives the error as "TypeError: f is undefined
...r[0];b=0;for(c=a.length;b<c;b++)f=l[b],f.nTf=a[b].cell,f.sClass&&h(f.nTf).addCla..." in jquery.dataTables.min.js
Please look at the example
https://jsfiddle.net/2ek0o1p6/

**Comment by DataTables** [comment]
> Uncaught ReferenceError: $ is not defined

It doesn't appear to be loading jQuery or DataTables. Can you link to a page showing the issue please.

**Comment by dskumarxd** [comment]
I can provide whatever information you want but I cannot link to the page,

**Comment by dskumarxd** [comment]
Please help me with the issue
