### ISSUE TITLE
Header table misaligned when using scrollY and Chrome at 110% zoom

### ISSUE THREAD

**Issue by jakezatecky** [DataTables/DataTables#479]
I had a user who was experiencing a misalignment in a DataTables header. This table was rendered using the `scrollY` option.

The user reported using Google Chrome, but I could not reproduce the behavior. Eventually, I stumbled upon some on old threads and found that a reference to this issue occurring only when the browser zoom is not at 100%. I can verify that this misalignment only occurs on Google Chrome when the zoom is not at 100%. Specifically, I can reliably recreate this issue if Chrome is set to 110%. Firefox and Internet Explorer do not experience this behavior.

Here's a simplified version of the initialization options that will cause this issue:

``` javascript
$table.dataTable({
    scrollY: "100px",
    scrollCollapse: true,
    paging: false,
    info: false,
    searching: false,
    data: data
});
```

See the following test case: http://jsfiddle.net/6L3Lp1Lo/

I know that `_fnBrowserDetect` is the culprit here, with `browser.bScrollbarLeft` incorrectly getting set to `true`, making DataTables think that this is a right-to-left layout. This value can cause some `padding-left` style to appear in the generated table header, causing the misalignment.

I can come up with a solution for my application, but this took some time to even reproduce, let alone figure out why was is occurring. Preferably, this LTR vs. RTL detection would be modified to be more accurate (possibly checking the markup for the `direction` attribute?). If not possible, it's probably reasonable to have an option to set the right-to-left to true or false. If that's not possible, could this scenario be documented on the website?

**Comment by DataTables** [comment]
Hi,

Thanks for the link. I have a feeling that the threads in the forum (or at least some) are from before the RTL support was added - so I don't think it is limited to just that. However, it would be good to resolve that, so I will try to look into it in future.

The problem with browser zooming is that each browser does it in a different way (reasonably so, since I doubt it is mandated in a W3C standard) which introduces a whole load of edge cases. I think in general, that browser zoom issues with scrolling is a low priority issue (sorry :-( ) - this is just relative to other issues that (imho - I might be wrong!) need to take priority.

**Comment by DataTables** [comment]
This was also brought up [in a separate issue](https://github.com/DataTables/Scroller/issues/44#issuecomment-76260771). I've got more information about the fix there, but basically it turned out to be a sub-pixel issue. A little workaround to have it working correctly is the correct thing to do here I think.
