### ISSUE TITLE
select2 in Responsive's child row: Shows all of select's options in portrait after shift from landscape

### ISSUE THREAD

**Issue by Xcellere** [DataTables/DataTables#483]
Using the select2 plugin along with DataTables Responsive. 

When the perspective of a mobile device is changed from landscape to portrait, and a parent row is clicked, any child rows using select2 lose their formatting and displays all of the select's options. Can be seen in the child row that begins with Expeditor.

This issue doesn't occur if the page loads in portrait.

![selectfilter](https://cloud.githubusercontent.com/assets/6492910/5859009/05592bf0-a20c-11e4-9016-6d1afa00fffd.jpg)

**Comment by DataTables** [comment]
When Responsive reads the data to show in the child row, it uses the `columns.render` function, rather than moving the DOM elements from the host cell to the child row ([code](https://github.com/DataTables/Responsive/blob/master/js/dataTables.responsive.js#L716)).

So what you would need to do is listen for the `column-visibility.dt` event and rebuild select2 when needed. Either that, or provide Responsive with a rendering method that will move the elements around rather than just copying the text.
