### ISSUE TITLE
jQuery UI: scrollX true - tbody center

### ISSUE THREAD

**Issue by ltdeta** [DataTables/DataTables#486]
I have a problem with the auto alignment of the table content. The header and content alignment changes diffrently when I change the size of the table.

example: [jsFiddle](http://jsfiddle.net/ltdeta/enb6ut9k/8/)

The thead and tbody are aligned to the left, if I set `scrollX` to true and maximize the window (this only happens if table content is bigger than table width). The thead alignmend is left but the tbody alignmend changes to center. 

the root cause might be found in the css file "dataTables.jqueryui.css"
```css
table.dataTable {
  margin: 0 auto;
```
it might be caused by the **auto** setting

**Comment by DataTables** [comment]
It is caused by the assignment of a fixed pixel width to every column. I would suggest using either percentage values (since absolute values don't really make must sense if you want wanted the table to resize horizontally) or leaving one or more columns without a static with assigned so the browser can take up the remaining space.

I take the point that the result is unexpected, but I think the input is also unexpected, so it likely isn't a case that DataTables will cope with. If it is fundamentally important for you, you could remove the margin from your local stylesheet.
