### ISSUE TITLE
Issue with _fnCalculateColumnWidths in jquery.dataTables.js introduced in DataTables v1.10.5 causing incorrect table width on redraw / recalc

### ISSUE THREAD

**Issue by cookch10** [DataTables/DataTables#501]
I was upgrading from DataTables `v1.10.4` to `v1.10.5` when I noticed that table width was incorrectly recalculated.

To reproduce the issue, I would load my page and render my table in a browser window sized at let's say 50% width.  When maximizing my browser window, the table would improperly redraw (table width was incorrect).  Refer to the following screenshots demonstrating the issue with `v1.10.5` (screenshots were taken from Google Chrome Version 40.0.2214.115 m, however the same issue was seen in Internet Explorer v11):

### Table on load with window not maximized:
![2015-02-24_1729-table-initialload](https://cloud.githubusercontent.com/assets/6051695/6361028/b81d05b8-bc4c-11e4-911e-0849e4894995.png)

### Table after load recalculated after window maximized:
![2015-02-24_1738-table-postload-widthrecalc](https://cloud.githubusercontent.com/assets/6051695/6361027/b81b8f80-bc4c-11e4-9ad4-29d29ab71c61.png)

The problem appears to lie with line 4081 in jquery.dataTables.js:
### Line 4081 in v1.10.4:
```javascript
    tableWidthAttr = table.style.width || table.getAttribute('width'), // from DOM element
```

### Line 4081 in v1.10.5:
```javascript
    tableWidthAttr = table.getAttribute('width'),
```

Swapping in the line from `v1.10.4` fixed the issue.

**Comment by DataTables** [comment]
Hi,

Thanks for flagging this up and also your analysis of the issue! The code I used was correct on the first width calculation of the table, but if rerun it would incorrectly use the pixel value it itself had assigned to the table...! 

I've [made a change](https://github.com/DataTables/DataTablesSrc/commit/67646fc2d94) so that it will only use the `style.width` property if it contains a `%`. Not perfect, but it should cover most cases.

There is [a discussion about this issue](https://www.datatables.net/forums/discussion/26284), with a test case, in the DataTables forums.

The fix is now in the [nightly](//datatables.net/download#Download) and in this repo. I'll probably release 1.10.6 next week as this is a horrible little bug.

**Comment by cookch10** [comment]
Thanks, Allan.  I verified that your update in the nightly `v1.10.6-dev` does resolve the issue.
