### ISSUE TITLE
deferRender appears to be broken

### ISSUE THREAD

**Issue by engineersamuel** [DataTables/DataTables#504]
I've done as much due diligence as I can and I still hold that I may be missing something here, but deferRender appears to not be working as I would expect it.  

I'm running 1.10.6-dev branch though I was on 1.10.5 with the same behavior.

I have a largish dataset of 7,430 objects.  The problem is it would appear all of cells are being rendered prior to the actual render of the page.  The page size is 10 and the column size is 11, so I would expect 110 renders.  Here is the output when I console.debug in the render function (I will show that later).
~~~
46908 datatable render called
7430 datatable render called
110 datatable render called
~~~

That output comes from this:
```javascript
        this.table = $(this.refs.table.getDOMNode()).dataTable({
            pagingType: "full_numbers",
            pageLength: 10,
            deferRender: true,
            processing: true,
            data: this.props.rows || [],
            columnDefs: [
                {
                    targets: '_all',
                    render: function(data, type, row) {
                        console.debug("datatable render called");
                        return (data != null ? data['f'] : void 0) || (data != null ? data['v'] : void 0) || data || '';
                    }
                }
            ]
        });
```

The `this.props.rows` is an array of objects that conform to the google table format, that let's me be pretty flexible with the output and should have no effect here.

The console.debug definitely slows things down, so removing that and adding a counter variable on this speeds things up, but still: `counter: 54448`

It would appear the array size * columns are being rendered, then not sure what 7430 is, then the 110 makes sense, that is the 10 page * 11.  

I have also tried an alternative way described here: http://www.nowherenearithaca.com/2015/03/avoiding-performance-gotcha-with-jquery.html but that didn't change anything, and led me to use 1.10.6-dev which had no difference in the # of render calls.

The big question I have, why is the render function ever invoked more than 110 times on the initialization of DataTable?

**Comment by DataTables** [comment]
I think you are misunderstanding the connection between `deferRender` and `columns.render` - the names are a bit confusing but they basically are not connected!

`deferRender` will tell DataTables not to create `tr` and `td` nodes until they are needed for the display. However, `columns.render` is required in order to figure out what rows are going to be displayed (as the information from that function will be used for sorting and filtering information).

`columns.render` is called every time DataTables needs to access data for that cell - that included sorting, filtering, type detection, etc. Hence why it is called multiple times.

A real test of if `deferRender` is working or not is to use `columns.createdCell` or `createdRow` to see when DataTables creates the cells / rows.
