### ISSUE TITLE
Table footer border width

### ISSUE THREAD

**Issue by bolemeus** [DataTables/DataTables#505]
I have a few tables on my page with a footer.
I noticed that the width of the border of the table cells of the footer are too thick.

The dataTables.bootstrap css that makes sure the boder width for the header are correct is:

```
table.table-bordered thead th, table.table-bordered thead td {
	border-left-width: 0;
	border-top-width: 0;
}
```

I expected somethiong similar for the table footer, but appearantly it isnt there, so I just added my own.

```
table.table-bordered tfoot th, table.table-bordered tfoot td {
	border-left-width: 0;
	border-bottom-width: 0;
}
```

**Comment by DataTables** [comment]
Thanks for letting me know about this. Fixed [here](https://github.com/DataTables/Plugins/commit/838d8df9c6b5a) and will be released soon.

Interestingly I expected the footer to have a double width border like the header does to separate it from the table body, but appears that this isn't how Bootstrap operates. So I've left it as how Bootstrap would style it rather than adding that extra border in (so basically your fix :-) ).
