### ISSUE TITLE
Hide Pagination Buttons When Pagination Is Not Possible

### ISSUE THREAD

**Issue by mjhasbach** [DataTables/DataTables#511]
If ```DataTable.models.oSettings.aoData``` <= ```DataTable.models.oSettings._iDisplayLength```, hide pagination buttons. Why are the "Previous" and "Next" pagination buttons visible when pagination is not possible?

[Here](http://datatables.net/forums/discussion/131/disabling-pagination-navigation-when-returning-only-one-page-of-results) is a 2009-2012 discussion that hasn't received any response from @DataTables since 2010.

[Here](http://stackoverflow.com/questions/11050826/disable-pagination-if-there-is-only-one-page-in-datatables) is a related Stack Overflow discussion.

Dynamically hiding pagination controls in ```DataTable.defaults.fnDrawCallback``` is hackish.

Thanks for DataTables. It is awesome.

**Comment by mjhasbach** [comment]
For future people who may read this, this is how I solved the problem in the short term:

```
fnDrawCallback: function() {
    var $paginate = this.siblings('.dataTables_paginate');

    if (this.api().data().length <= this.fnSettings()._iDisplayLength){
        $paginate.hide();
    }
    else{
        $paginate.show();
    }
}
```

**Comment by DataTables** [comment]
Rather than using the private settings object I would suggest just using the public API to achieve this. For example:

```
    $(table.table().container())
      .find('div.dataTables_paginate')
      .css( 'display', table.page.info().pages <= 1 ?
           'none' :
           'block'
      )
```

[This is that running](http://live.datatables.net/xanoleyu/1/edit) using the `draw` event - you could also use `drawCallback` if you wanted.

Is there a bug somewhere that you wanted to highlight in this issue or did you just want to document how this can be done?

**Comment by mjhasbach** [comment]
@DataTables thanks for the suggestion. Your solution is more elegant than mine.

My point was that I feel the pagination buttons should be hidden by default when pagination is not possible, because they serve no purpose. I feel they are an eyesore when ```DataTable.models.oSettings.aoData``` <= ```DataTable.models.oSettings._iDisplayLength```. In my opinion, ```DataTable.models.oLanguage.sInfo``` and ```DataTable.models.oLanguage.sInfoEmpty``` give a sufficient enough indication that pagination is not possible.

**Comment by jhfrench** [comment]
I disagree with this sentiment. I agree with your original premise ("If `DataTable.models.oSettings.aoData <= DataTable.models.oSettings._iDisplayLength`, disable pagination buttons"), but *showing/hiding* the control is a more obtrusive UX that enable/disable.

**Comment by DataTables** [comment]
It is down to personal preference I think. I'm not going to be integrating this into DataTables core, which will continue to always show the paging buttons if they are enabled as it currently does, but the option (code above) is now available should anyone want to use this.

Thanks for bringing this up @mjhasbach

**Comment by mjhasbach** [comment]
@jhfrench I agree that some people may find the pagination buttons suddenly appearing / disappearing to be jarring. ```$.fadeIn()``` and ```$.fadeOut()``` would help, and that is the route I will most likely go with in my project. Having that functionality built in to DataTables would be cool, though.

Something like ```DataTable.models.oSettings.bConditionalHidePagination``` could hide / show the pagination buttons when ```DataTable.models.oSettings.aoData``` <= ```DataTable.models.oSettings._iDisplayLength``` and ```DataTable.models.oSettings.bConditionalHidePaginationTransition``` could control whether or not the pagination buttons fade in / out. I'm not suggesting that should be the default behavior, but I feel it is a feature that many would benefit from.

**Comment by DataTables** [comment]
As I noted above, not something that I am currently considering for inclusion in DataTables core, but something that would be suitable as [a feature plug-in](https://github.com/DataTables/Plugins/tree/master/features).

Also, I would recommend staying away from the private interface of the settings object. The properties in it can, will and do change between versions - it is not a public API. I would suggest using the public API as much as possible - if you need data that isn't available from the public API let me know and I'll consider adding it.

I don't think there is actually a bug here, so going to close this issue now. The GitHub issues list I would like to keep for bugs only, general discussions are more suited for the [forums](//datatables.net/forums) (simply because there is only one of me and a _lot_ of support requests, so would like to channel them).

**Comment by mjhasbach** [comment]
@DataTables I will consider making a feature plugin.

Thanks again for the public API advice.

I will submit future suggestions to the forum. Have a good weekend.
