### ISSUE TITLE
ajax.reload() do not respond when using ajax option

### ISSUE THREAD

**Issue by klarkc** [DataTables/DataTables#524]
When you use the new ajax option (http://datatables.net/reference/option/ajax) the ajax.reload() function does not work appropriately.

First example (not working): http://jsfiddle.net/cru97z69/

But when you use the legacy sAjaxSource option (http://legacy.datatables.net/usage/server-side) the ajax.reload() function work normally.

Second example (working): http://jsfiddle.net/cp3hd8pv/1/

The same bug is reproducible with ajax.url().load() function.

**Comment by klarkc** [comment]
Looking at debug information, the data is being loaded from the server, so the problem is when reload call the callback (?)

**Comment by DataTables** [comment]
I think the problem is that when you use the `ajax` option of DataTables 1.10 it sends the server-side processing request with different (camelCase) parameters from the old style 1.9- legacy parameters. The result is that your server-side processing script is returning the draw counter as 1 always.

If you enable the legacy mode it works okay: http://jsfiddle.net/cru97z69/1/ .

See [the docs](http://datatables.net/manual/server-side#Legacy) for more information about the new and legacy modes.
