### ISSUE TITLE
Something strange with register

### ISSUE THREAD

**Issue by Vaflan** [DataTables/DataTables#544]
If you create a table with an upper letter **D**ataTable(); (1.10.6)

    DataTable().fnSetColumnVis(0, false); // - does not work!
    DataTable().ajax.reload(); // - work!
    DataTable().column(0); // - work!

And if with a lower letter **d**ataTable();

    dataTable().fnSetColumnVis(0, false); // - work!
    dataTable().ajax.reload(); // - does not work!
    dataTable().column(0); // - does not work!

Who can say why?

Example: http://jsfiddle.net/Vaflan/o0mcc97L/

**Comment by Misiu** [comment]
Per the [contributing document](https://github.com/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](https://datatables.net/support).
http://datatables.net/manual/api#Accessing-the-API
This might help You:
```
var table = $('#example').DataTable();
// Hide a column
table.column( 1 ).visible( false );
```
Also please notice that since 1.10 API has change, I propose that You look at official site for changes and getting started instructions.

**Comment by DataTables** [comment]
See also the [second top FAQ](//datatables.net/faqs/#api).
