### ISSUE TITLE
Include columns[i][visible] in Server-Side Processing Sent Parameters 

### ISSUE THREAD

**Issue by mjhasbach** [DataTables/DataTables#549]
The server-side processing sent parameters should include columns[i][visible] in order to facilitate column hiding.

**Comment by DataTables** [comment]
I've actually had quite a number of comments (/complaints) about the number of parameters being sent by DataTables for server-side processing, so I'm reluctant to add any more without a significant reason. In this case are you using the hidden columns so that they aren't included in the SQL and therefore saving a little bit of processing time? The downside is that many cases (Responsive for example) actually still use the hidden information.

[The `ajax.data` option](http://datatables.net/reference/option/ajax.data) can be used if you want to send additional parameters such as this to the server.

**Comment by mjhasbach** [comment]
> are you using the hidden columns so that they aren't included in the SQL and therefore saving a little bit of processing time?

Yes. SQL processing time and bandwidth between the client and server.

> The ajax.data option can be used if you want to send additional parameters such as this to the server.

Thanks. I will explore that option if I need to implement hidden columns.
