### ISSUE TITLE
scrolX/scrolY -> placing third party plugins into table headers.

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#593]
Hi,

I wonder if you can help with the following issue, when using the scrolX/Y and placing and using a plugin such as chosen (same with others) in table header I bumped into the follwing issue, since the `dataTables_scrollHead` got the following css rule `overflow: hidden;` the chosen element is being hidden and cannot be seen, so the only solution I found is the set `.dataTables_scrollHead {overflow: visible !important;}` , but then , when using the horizontal scroll the table header wont move along with the scroller and instead will freeze, so eventually the usage of the `.dataTables_scrollHead {overflow: visible !important;}` is not good enough.

Any idea?

Test cases: [filters wont open / headers will scroll](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_source_chosen.html)

Test case: [filters open / headers wont scroll](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_source_chosen_visible.html)

https://github.com/vedmack/yadcf/issues/43#issuecomment-118832177

Thanks!

Daniel

**Comment by DataTables** [comment]
Hi Daniel,

So the issue here is that the Chosen plugin will insert its display elements into the parent of the host element. It does that to ensure that the items will remain anchored to that element as it moves around the display. The issue of course is that DataTables must have the overflow property set to hidden otherwise scrolling simply won't work.

For this reason, Chosen might not be suitable for this application. Select2 takes a different approach and inserts its display elements into the document, making it more appropriate for this use case. On the plus side DataTables scrolling and the input control will both work. On the downside, if you scroll the DataTables viewport while the control is visible (if Select2 even allows that) you might need to call a Select2 API method to reposition the input display.

So probably not the answer you want I'm afraid, but because of the way Chosen works, it simply isn't suitable for display in the header. This will likely apply to other controls as well.

**Comment by vedmack** [comment]
Ok, 

Thanks Allan,
