### ISSUE TITLE
SECURITY FLAW: Veracode identifies Cross Scripting with unit testing php files

### ISSUE THREAD

**Issue by patrot** [DataTables/DataTables#602]
The following php files have Cross Scripting risks reported by Veracode

The Veracode error is CWE-80: Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS) and link is http://cwe.mitre.org/data/definitions/80.html

media/unit_testing/templates directory

![image](https://cloud.githubusercontent.com/assets/7143918/8702959/7028122c-2ae0-11e5-9286-d6ae54ec9551.png)

media/unit_testing/performance directory

![image](https://cloud.githubusercontent.com/assets/7143918/8702977/8dd5bca2-2ae0-11e5-8b35-eb751204f43b.png)

examples/server_side/scripts directory

![image](https://cloud.githubusercontent.com/assets/7143918/8702998/a6555a26-2ae0-11e5-8a29-da77c1c0afa1.png)

**Comment by DataTables** [comment]
Hi - thanks for posting this. The issues in the unit_testing aren't great, but I don't see them as being critical since that should _never_ be deployed on a production server. I'm not even aware of anyone other than me running it since it is in a poor state of health atm...

Most of the SSP issues seem to be concerned about the $_GET or $_POST arrays being passed to the SSP class, which as far as I am aware does not have any security issues - everything is correctly bound to a PDO instance.

The JSONP callback however is a nasty little one. I've just [committed](https://github.com/DataTables/DataTablesSrc/commit/76239c30543) a change that validates it before being used.

**Comment by DataTables** [comment]
The templates issue has [now been fixed](https://github.com/DataTables/DataTablesSrc/commit/ccf86dc5982bd8e16d) in the src repo and the unit tests removed from this built repo.

Thanks again for posting this.
