### ISSUE TITLE
Useless horizontal scrollbar when many records and few columns. 

### ISSUE THREAD

**Issue by Delgan** [DataTables/DataTables#609]
Hello.

I encountered a slight bug using DataTables (great tool also thank you for your incredible work).

The issue occurs while `scrollX` and `scrollY` are enabled when there are many records and few columns. 
What happens is that the vertical scrollbar is correctly displayed, but the horizontal one is displayed whereas there is no need for it. Actually, it looks like the horizontal scrollbar is including the vertical one while computing the length of the table.

It is a little bit complicated to explain that, so here is a JSFiddle: https://jsfiddle.net/dLm0d1fs/6/

![Screen](https://cloud.githubusercontent.com/assets/4193924/8874215/19e5376a-320f-11e5-8aeb-5bd71dd40faf.png)

I am using Firefox 38.0.6 and DataTables 1.10.7.

I hope this issue was not already reported.

**Comment by DataTables** [comment]
It looks like horizontal scrolling probably is required in your screenshot. The header elements have a fair amount of padding on them forcing the width. If you reduce that padding I suspect your problem will be resolved.

**Comment by Delgan** [comment]
I tried setting the padding to `0px` but the issue is still the same: https://jsfiddle.net/dLm0d1fs/7/

**Comment by DataTables** [comment]
Thanks for the update - apologies, you are absolutely correct.

What is happening is that when the DataTable is first constructed DataTables will calculate the column widths to be used. This happens _before_ the data has been added to the document (from the `data` property). The result is that the column widths calculated do not take into account the scrollbar width, since at that time, there is no need for scrolling (there is no data!).

Then the data is added, and there is a need for the scrollbar, at which point the calculations are off.

Called the `columns.adjust()` method can be seen to address this: https://jsfiddle.net/dLm0d1fs/8/ .

So the fix is going to have to be calculating the column widths after the data has been added - I'll look into that.

**Comment by DataTables** [comment]
[Fixed committed here](https://github.com/DataTables/DataTablesSrc/commit/f2df071604c8a). And [updated example](https://jsfiddle.net/dLm0d1fs/9/).

Wasn't what was planned for today's work, but a good thing to do - thanks for flagging this issue up :-)

**Comment by Delgan** [comment]
Thank you for having fixed it so quickly, your work is very impressive!
