### ISSUE TITLE
Not working examples on new release

### ISSUE THREAD

**Issue by Misiu** [DataTables/DataTables#621]
Hi Allan, first of all congratulations on new release, can't wait to test all those new features!

I've noticed that some examples aren't working. For example colvis (http://datatables.net/extensions/buttons/examples/column_visibility/simple.html) shows error:
![snap 2015-08-13 at 18 22 13](https://cloud.githubusercontent.com/assets/1741838/9255236/3cd0d3fe-41e8-11e5-9ee9-0824b92e897f.png)
basically all examples that use this script (available from here: http://datatables.net/extensions/buttons/examples/column_visibility/index.html)

Hopefully errors I found are the only ones in this release.
Weekends coming, so I'll have some time for testing :smile:

**Comment by DataTables** [comment]
Thanks for pointing that out. It was just a file case issue that I didn't spot prior to deployment because of the non-case sensitive file system on MacOS. `colvis` should have been `colVis`.

I've updated the examples so they work now, but as the packages have been tagged and deployed with the typo I've also added a redirect into the CDN to the typo will still resolve for this version of Buttons. It will not for the next.

Regards,  
Allan
