### ISSUE TITLE
CDN link built using Download Builder not working

### ISSUE THREAD

**Issue by gauravmak** [DataTables/DataTables#622]
Link - https://cdn.datatables.net/r/dt/jszip-2.5.0,pdfmake-0.1.18,dt-1.10.8,b-1.0.0,b-flash-1.0.0,b-html5-1.0.0,b-print-1.0.0,r-1.0.7,se-1.0.0/datatables.min.js
Bring an error **Error: Build is incomplete**

**Comment by DataTables** [comment]
A mistake in my CDN builder. Basically the CDN will use the download builder and wait for a little while for builder to complete. If it hasn't completed in the available time it gives the error you were seeing.

The issue was that it was waiting for a maximum of `3mS` not `3S` has I had wanted... Fixed now :-)
