### ISSUE TITLE
ColReorder reorderCallback fires on load/initialization

### ISSUE THREAD

**Issue by jamezamm** [DataTables/DataTables#629]
I noticed that in recent versions (1.1.3 & 1.20), the **reorderCallback** fires immediately on table initialization. This wasn't the case in colreorder version 1.1.2.

A test case showing this issue: http://live.datatables.net/gihuhigu/1/edit . Make sure you hit **Run with JS** Button.

I debugged the code and the callback seems to fire after it sets the order from the saved state.

**Comment by DataTables** [comment]
Hi,

Thanks for letting me know about this. I've just [committed the required fix](https://github.com/DataTables/ColReorder/commit/c4f4e79a26). Basically, because you have state saving enabled it was spinning through the saved array and then triggering the callback, even if nothing had changed. I've changed it so no callback will be triggered is there is no change.
