### ISSUE TITLE
column().visible() bugs after 2 uses.

### ISSUE THREAD

**Issue by elfif** [DataTables/DataTables#645]
Hello .

I Think i detected a bug using the visible function.
I use that function to split my datatable columns. Here is an example.
My datatable has 12 visible columns. She loads without a problem.

To make it easier to understand i did a dirty and simplified jsFiddle [here](http://jsfiddle.net/HEDvf/3060/)
You need to run it a second time to see the problem. After  the view 2 Ok message you will notice that columns and columns title doesn't match anymore. They were ok at the start, ok on View 1 Ok message but not after the second change.

**Comment by elfif** [comment]
Hi there.

I managed to find a workaround, [here it is](http://jsfiddle.net/HEDvf/3061/)
Hope it helps.

**Comment by DataTables** [comment]
I don't understand I'm afraid. In what way are they not okay? This screenshot is from my second load on your JSFiddle:

![screen shot 2015-08-25 at 09 36 55](https://cloud.githubusercontent.com/assets/278219/9462372/4846bd38-4b0d-11e5-85a1-1a90b5f563af.png)

**Comment by elfif** [comment]
Well what is not okay is that column named platform should be named Css Grade, in fact the "platform(s)", "engine version" and "CssGrade" columns doesn't match their original content.

**Comment by DataTables** [comment]
Thank you for the explanation. The issue is that you are passing an invalid value into the `column().visible()` method. As the [documentation notes](http://datatables.net/reference/api/column().visible()) it expects a boolean value, while you were passing it a number. If you pass in a boolean it works as expected: http://jsfiddle.net/HEDvf/3062/ .
