### ISSUE TITLE
_selector_run causes maximum call stack size exceeded

### ISSUE THREAD

**Issue by appsbychris** [DataTables/DataTables#651]
In ```"_selector_run"``` function, about ``` line 7581 ```
The array.push.apply method is causing this error in chrome.
```javascript
out.push.apply( out, res );
```
If ```res.length``` is like ```130000```, it will cause the error.

If you type this in chrome console:
```javascript
var arr = [];
arr.push.apply(arr, new Array(130000));
```
You will see this error:
```javascript
VM581:4 Uncaught RangeError: Maximum call stack size exceeded(…)
```

Only workaround i have found is to just loop ```res```, and ```push``` 1 at a time.

**Comment by DataTables** [comment]
Very interesting - thanks for posting this. I [found this webkit bug](https://bugs.webkit.org/show_bug.cgi?id=80797) on the topic.

I should really use `Array.concat` for this I think. Even IE6 supports it, so that is probably the way to go.

Interestingly, [this jsperf](http://jsperf.com/array-prototype-push-apply-vs-concat/20) appears to show that the for loop is the fastest option, but I've used this option in a number of different places in the code, and the concat makes a lot more sense.

I'll post back when committed to the various parts of the library.

**Comment by DataTables** [comment]
A combination between `concat` and `$.merge()` do the job nicely. Funny that Javascript doesn't have such a function built in...

Thanks for raising this.
