### ISSUE TITLE
Details rendered event

### ISSUE THREAD

**Issue by carrpirates** [DataTables/DataTables#668]
Is there any details rendered event for responsive extension ?
I need to re-bind some plugin to cells content when the new details has been rendered to dom.
I tried to listen column-visiblity.dt event but it didn't work.

**Comment by DataTables** [comment]
As in child rows? No there isn't at this time since the child row is under control of the calling software, so it would generally know when it is displayed so there is no need for DataTables to emit an event.

In future, per the contributing document that GitHub links to on the "new issue" page, could you open support requests / questions in the [DataTables forums please](//datatables.net/forums).
