### ISSUE TITLE
Event handlers removed on elements inside cells with data-order or data-sort attribute

### ISSUE THREAD

**Issue by simonbrent** [DataTables/DataTables#684]
Here is an example: http://jsbin.com/sewiyuvifi/edit?html,js,console,output

(originally based on https://datatables.net/examples/advanced_init/html5-data-attributes.html)

Three cells have a link saying "Click me!", all of which have the same event handler attached - to log "clicked!" when clicked. The link in the first cell works as expected, but the other two, which have a data-sort and a data-order attribute respectively, do not.

It appears that the .click elements in the latter two cells have been removed from the DOM, and the content now displayed there are clones of those elements which do not have their event handlers attached.

**Comment by DataTables** [comment]
That's a bit odd - thanks for pointing that out. I don't have an immediate answer for why this is happening, but I do have a suggestion - if you use a delegated event handler it will work: http://jsbin.com/tanudupetu/1/edit?html,js,console,output . In general this is better practice for a DataTable any way since it negates any issues with sorting etc.

Having said that, I don't see why your test case doesn't work - I'll look into it.

**Comment by DataTables** [comment]
Finally fixed :-)
