### ISSUE TITLE
Make the columnSearch customs

### ISSUE THREAD

**Issue by danicomas** [DataTables/DataTables#710]
```js
for ( i=0 ; i<columnCount ; i++ ) {
			column = columns[i];
			columnSearch = preColSearch[i];
			dataProp = typeof column.mData=="function" ? 'function' : column.mData ;
	
			d.columns.push( {
				data:       dataProp,
				name:       column.sName,
				searchable: column.bSearchable,
				orderable:  column.bSortable,
				search:     columnSearch
			} );
	
```

instead than (https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.js#L2693)

```js
for ( i=0 ; i<columnCount ; i++ ) {
			column = columns[i];
			columnSearch = preColSearch[i];
			dataProp = typeof column.mData=="function" ? 'function' : column.mData ;
	
			d.columns.push( {
				data:       dataProp,
				name:       column.sName,
				searchable: column.bSearchable,
				orderable:  column.bSortable,
				search:     {
					value: columnSearch.sSearch,
					regex: columnSearch.bRegex
				}
			} );
	
```

**Comment by DataTables** [comment]
Thanks for posting this. Could you clarify what the intention of the change is - I'm not quite clear on that. I realise of course that it passed the columnSearch object in, but what is the advantage?

**Comment by danicomas** [comment]
Sorry @DataTables, I want to do something like that:

```js
var settings = $("#tests_list").DataTable().settings();
settings[0].aoPreSearchCols[0].sType = 'kkkkk'; //custom search field to receive in the server

$("#tests_list").DataTable().column(columnSelected).search(
				valueSelected,
				"false",
				"true"
			).draw();
```

```
//the best practise would be include something like that too //$("#tests_list").DataTable().column(columnSelected).search(customObject) too
```

**Comment by DataTables** [comment]
I understand - thanks for the clarification. I think your best practice suggestion is a good one and this is actually something I want to be able to provide in the next major version of DataTables.

Until then, I don't think this is something I want to add to DataTables since the presearch object contains other information that possibly shouldn't be submitted to the server (the GET url strings are already long enough!). Also, and more importantly, it would cause the parameter names to change from `search` to `sSearch`. For that reason, I'm going to close this request at the moment, but with the plan to provide something like what you really want in future.

**Comment by danicomas** [comment]
Ok thanks @DataTables

**Comment by danicomas** [comment]
The workaround now is to do something like that @DataTables:

previous server call:
```js
"data": function ( d ) {
	var settings = $("#tests_list").DataTable().settings();
	//and iterate d.columns with = settings[0].aoPreSearchCols data
}
```

custom fild in the search col
```js
var settings = $("#tests_list").DataTable().settings();
			settings[0].aoPreSearchCols[0].sType = 'kkkkk'; //we add sType field

			$("#tests_list").DataTable().column(columnSelected).search(
				valueSelected,
				"false",
				"true"
			).draw();
```
