### ISSUE TITLE
datatables version 1.10.10 don't support requirejs?

### ISSUE THREAD

**Issue by HengCC** [DataTables/DataTables#726]
i use 'bower update'  command  and the datatables was upgrade to version 1.10.10  from 1.10.9,

but when i restart my server,i got the problem:"Uncaught Error: Script error for: datatables.net"

and i use chrome dev-tools  to see the network , i find  requirejs was try to load 

"http://****/datatables.net.js" , 

my requirejs config file :

"datatables":"libs/datatables/js/jquery.dataTables",
"datatables.bootstrap":"libs/datatables/js/dataTables.bootstrap",
"datatables.responsive": "libs/datatables-responsive/js/datatables.responsive",
"datatables.columnfilter": "libs/jquery-datatables-columnfilter/jquery.dataTables.columnFilter",
"datatables.fixedcolumns": "libs/datatables-fixedcolumns/dataTables.fixedColumns",

"datatables": ["jquery"],
"datatables.bootstrap":["bootstrap"],
"datatables.responsive":[
         "css!libs/datatables-responsive/css/datatables.responsive.css"
 ],
 "datatables.fixedcolumns":[
          "css!libs/datatables-fixedcolumns/fixedColumns.dataTables.css"
 ],
"datatables.columnfilter":[
          'jquery'
 ],

**Comment by DataTables** [comment]
Hi,

So this is a bit of a screw up on my part - apologies. In 1.10.10 the Bootstrap stuff will do `require('datatables.net')` which is where that is coming from. It does that so I could publish deployment packages with consistent naming on bower and NPM. All of the extensions (Responsive etc) saw a major version bump because of that change - that was the correct way to do it.

However, I didn't see the need for a DataTables major version bump because the change wasn't particularly relevant in the core - with the exception of the styling integrations. That's what I forgot about and where the screw up is.

So its not wrong as such, but it should probably have been released as 1.11 because of the styling integration.

You can probably add:

```
"datatables.net":"libs/datatables/js/jquery.dataTables",
```

or perhaps bower lets you do a proper alias which would be even better...

So, sorry about this - it is an intentional change, but it should have been a bigger version bump.

**Comment by DataTables** [comment]
Going to close this issue now based on my above comment.

**Comment by louisl** [comment]
@DataTables This change has also broken dataTables.colVis.js and dataTables.tableTools.js they both require 'datatables' instead of 'datatables.net'

**Comment by DataTables** [comment]
ColVis and TableTools are both retired software now and are not receiving any further development (save security fixes should any be required). Buttons and Select replace the two older extensions.

**Comment by louisl** [comment]
OK, thanks for the info. I hadn't noticed they were retired, I will look into updating to those two from here on.

**Comment by julmot** [comment]
@DataTables 

I've also come here because [this file on the CDN](https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js) is requesting `datatables.net`.

> In 1.10.10 the Bootstrap stuff will do require('datatables.net') which is where that is coming from. It does that so I could publish deployment packages with consistent naming on bower and NPM.

Sorry, I don't understand this. Could you please tell me the reason for naming it `datatables.net` instead of `datatables`?

I see a few files using `datatables` and not `datatables.net` in their `define` on first glance:

- https://github.com/DataTables/Plugins/blob/master/sorting/datetime-moment.js
- https://github.com/DataTables/Plugins/blob/master/integration/foundation/dataTables.foundation.js
- https://github.com/DataTables/Plugins/blob/master/features/mark.js/datatables.mark.js
- https://github.com/DataTables/Plugins/blob/master/integration/bootstrap/3/dataTables.bootstrap.js (which I don't understand, because as mentioned above, the file on the CDN is requesting `datatables.net`)
- https://github.com/DataTables/Plugins/blob/master/integration/jqueryui/dataTables.jqueryui.js

Maybe I'm misunderstanding something but this seems to be inconsistent?

**Comment by DataTables** [comment]
> Could you please tell me the reason for naming it datatables.net instead of datatables?

Naming consistency. A while back DataTables defined itself as a named module (`datatables`) but that is frowned upon, so when I removed that and updated the AMD and CommonJS loaders I also made distribution packages for npm and bower. In order to be able to publish these packages with a consistent naming structure, I used `datatables.net` rather than the old one which already had some packages registered by me (which would cause backwards compat issues) and packages not registered by me, which I couldn't control.

As I noted above, it was a mistake to do this without a major version bump. Lesson learned.

The integration files in the Plugins repo should actually be removed and are no longer current since the integration is now part of each library rather than in the plug-ins repo. Thanks for reminding me to do that. I've committed a fix for the datetime-moment file (although it still needs a CommonJS loader).

**Comment by julmot** [comment]
@DataTables 

> I used datatables.net rather than the old one which already had some packages registered by me (which would cause backwards compat issues) and packages not registered by me, which I couldn't control.

I'm sorry to ask further questions, but I'm still confused. It seems like that the `datatables` package on npm is the source package, while `datatables.net` is the dist package. If this is true, then:

- Why is the source package actually registered on npm? A user would normally not install source files but only distribution-ready files. So why is it necessary to ship source files?
- Why is the suffix named `.net` and not `-dist`?

> and packages not registered by me, which I couldn't control.

You mean that `datatables.net` now is your unique prefix?

Thank you in advance!

**Comment by DataTables** [comment]
> Why is the source package actually registered on npm?

This isn't a source repo - it is a legacy distribution repo. The src repo is DataTablesSrc. The only reason this repo is available on npm is legacy reasons. I'm not going to remove it because a lot of people still use it. It is kept in sync with the src repo.

> Why is the suffix named .net and not -dist

Just cos :-). The `.net` suffix seemed to make sense to me at the time.

> You mean that datatables.net now is your unique prefix?

Nothing to stop people grabbing other similar names, but hopefully they will leave them for the "official" packages.

**Comment by julmot** [comment]
@DataTables Thank you! This clarified the situation for me.
