### ISSUE TITLE
[Sorting] Handle upper and lower case

### ISSUE THREAD

**Issue by Tomino2112** [DataTables/DataTables#739]
I have just spent half an hour trying to figure out why my `[[2, 'DESC']]` sorting doesn't work, apparently sorting handles only `asc` or `desc` values (lowercase) but not `ASC` / `DESC` values. I simple `direction.toLowerCase()` implementation would be great as many people are used to work with uppercase from working with DB.

**Comment by DataTables** [comment]
It is [documented](http://datatables.net/reference/option/order) as `asc` and `desc`, however I take the point and will look at adding this.

**Comment by DataTables** [comment]
Just been looking into this, and it is actually possible using the current code to specify your own sorting plug-ins that could use something like `ASC` or `Asc` rather than `asc`. So changing the code to use `toLowerCase()` could actually cause issues with backwards compatibility. I'm not sure if anyone is using it that way, and I wouldn't recommend it, but it is possible.

As such, since the use of `asc` and `desc` is the documented style I'm not going to make the change for now. That might change with the next major revision of DataTables where I plan to change how the ordering can operate there.
