### ISSUE TITLE
Accessing columnDefs render or data functions while inside $.fn.dataTableExt.afnFiltering

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#742]
HI,

I wondered if I can access the columnDefs `render` or `data` functions while doing range filtering on the table, [thats my code atm](https://github.com/vedmack/yadcf/blob/de66d422825d511e9f6a1fb18747f034d3e7fdd5/jquery.dataTables.yadcf.js#L1131) , and thats the [test case](https://jsbin.com/samoxiyegi/edit?html,js,console,output). if I'll have access to the `render` or `data` functions it will simplify the filtering process.
I know that the visible value (after the apply of the `render` or `data` can be found inside the second argument `aData`, but I can't recall why eventually I prefered to use the fourth argument as the source of the column value :|

Thanks

https://github.com/vedmack/yadcf/issues/262

**Comment by DataTables** [comment]
You can request the rendered data for a cell using [`cell().render()`](http://datatables.net/reference/api/cell().render()). There is also a [plural version, `cells().render()`](http://datatables.net/reference/api/cells().render()) if you want the data for a whole row or column.

Allan

**Comment by vedmack** [comment]
Can I access it inside my `function (settingsDt, aData, iDataIndex, rowData) {` function? 
If yes than how?

**Comment by DataTables** [comment]
You would need to do `var api = new $.fn.dataTable.Api( settingsDt );`. Then `api.cell().render()`. You might want to keep a local cache of the API instance (look it up by the settings object for example) otherwise you'd ned creating a new API instance for every call of that function which could be quite slow.

However, the data passed in as the second parameter should be the filtering rendered data already. [This little example](https://jsbin.com/darelomoza/edit?html,js,output), based on the example in your linked thread, appears to confirm that.
