### ISSUE TITLE
Sorting column redirect to first page

### ISSUE THREAD

**Issue by joko-wandiro** [DataTables/DataTables#748]
While user select fourth page then do sorting column redirect to first page why  doesn't make it keep on the current page ( to be default configuration of dataTables ).

I try to check it and get the following result.
I get description about holdPosition parameter from DocBlock Comment to Keep the current paging position. By default the paging is reset to the first page. Why doesn't make it available to set from DataTable Options.

<pre>
<code>
/**
 * Redraw the table - taking account of the various features which are enabled
 *  @param {object} oSettings dataTables settings object
 *  @param {boolean} [holdPosition] Keep the current paging position. By default
 *    the paging is reset to the first page
 *  @memberof DataTable#oApi
 */
function _fnReDraw( settings, holdPosition )
...
if ( holdPosition !== true ) { // holdPosition undefined variable
	settings._iDisplayStart = 0;
}

// Let any modules know about the draw hold position state (used by
// scrolling internally)
settings._drawHold = holdPosition;
</code>
</pre>

It just my opinion holdPosition parameter should be removed from method and add holdPosition as DataTable Options so user can decide IF sorting go to first page or not. You can check on the following code, i haven't test it yet but it should works properly.

<pre>
<code>
function _fnReDraw( settings )
...
if ( settings.holdPosition !== true ) {
settings._iDisplayStart = 0;
...
</code>
</pre>

I try to handle it using preDrawCallback and it works properly.
Here's the code, I detect it using settings._drawHold value which assigned with undefined variable.

<pre>
<code>
"preDrawCallback": function( settings ) {
	if( typeof(settings._drawHold) == "undefined" ){
		tableID= $(settings.nTable).attr("id");
		currentPage= $('#'+tableID+'_paginate 

.paginate_button.current').html();
		settings._iDisplayStart = (parseInt(currentPage)-1) * 

settings._iDisplayLength;
	}
},
</code>
</pre>

**Comment by DataTables** [comment]
The behaviour of dropping the paging back to the first page when you sort a column is entirely intentional - my reasoning for this is that it would make little sense to retain the paging which has no navigational relationship to the data that has been sorted. For example consider you have a list of names and ages for staff members. You are initially sorting by name and go to page four. If you then sort by age, why would you want to remain on page four when you have no context to what that data means? I would expect to be dropped back to the first page so I do have some context (the lowest or the highest age) and can then navigate through the dataset rather than being placed into the middle of it.

This isn't something that I plan to change in DataTables - is a question that has only come up a couple of times during its 9 year existence and I think the majority of users are happy with the current behaviour. As such I'm going to close this issue, but I'm happy to continue the discussion if you have a use case for which this would be particularly useful.

**Comment by joko-wandiro** [comment]
I get a task from client request want to display data according to the current page while do sorting functionality.

**Comment by jvanveen** [comment]
We are trying to do the same thing. +1 for an option to keep the current page active.
