### ISSUE TITLE
Console error message when window resized, IE only

### ISSUE THREAD

**Issue by ajwaddell** [DataTables/DataTables#757]
I am using DataTables v1.10.10 with `scrollY` turned on. 

The issue I am having is when `DataTable().columns.adjust()` is called and then a new table is loaded via jQuery, when the browser window is resized I get th e following error message in the console.

`Unable to get property 'style' of undefined or null reference`

The error only occurs in IE.
I have created a jsFiddle to recreate the issue https://jsfiddle.net/ajw89/3b8swp0v/

I have traced the issue back and it seems to have been introduced at v1.10.5.  Within `_fnCalculateColumnWidths()` it is binding a resize event onto the window for each table.  This event is not being removed so when I destroy the table then initialise a new table with the same ID, it will have 2 resize events bound to it.  When the window is resized the settings must be corrupt for the table that has been destroyed because it can't get the table headers.

If I run the following code prior to initialising the DataTable everything works as expected .
```javascript
$(window).unbind("resize.DT-"+table_id);
```

**Comment by DataTables** [comment]
The problem here is that you can't just remove the table by overwriting it in the DOM using `$().html()`. The DataTable instance will still exist, even if the table doesn't in the DOM - indeed this is a sure fire way of getting a memory leak on the page.

So what is happening is that the window resize event listener for the original table is still triggering (which you really don't want!). The "fix" is to destroy the old table which you can to with the `destroy()` API method: https://jsfiddle.net/3b8swp0v/5/
