### ISSUE TITLE
Select inside a responsive table not working when using column controlled child rows

### ISSUE THREAD

**Issue by tbrcrl** [DataTables/DataTables#768]
Hi to everybody, the summary of the issue is reported here below.

Way to reproduce
Build a responsive datatable and insert a series of select inside a column.
In addition, use “control column” as the control of the responsive child rows.
A live demo is shown in
http://live.datatables.net/xewuluvu/2/edit

Results
The selects in the table cells are not selectable (the dropdown does not open as expected).
This happens also if
- the control is not yet present and hence the columns are not yet wrapped
- the control is present but the select are not wrapped in the child row.
Cause of the issue
The issue is caused by the use of “control column” (the control is present in a dedicated column) as the control of the responsive child rows.
If the default “inline” method (the control is present in the same column of the content) is used, the issue disappears and the select in the cells work correctly.
Any suggestion or workaround to solve the issue? (apart the already mentioned use of the “inline” method?).

Thanks

**Comment by DataTables** [comment]
Thanks for your question. However, per the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) please post support requests in the [DataTables forums](//datatables.net/forums).

The issue here is that you need to use Responsive 2.0.2 rather than 2.0.0 in your example: http://live.datatables.net/xewuluvu/5/edit .

Note also that the select element in the child row is not the same element as shown in the DataTable. The value would need to be synced externally if you want to use it in both.
