### ISSUE TITLE
Empty Row = Colspan 0

### ISSUE THREAD

**Issue by datasage** [DataTables/DataTables#771]
With the last release I noticed 2 new problems with my tables. My tables are created with in a variety of ways, some with html and most with ajax. In some cases tables are initialized while hidden.

1. Empty row td gets a colspan of 0. Appears to be related to being initialized while hidden. Doesn't affect all tables. 

2. Some tables loose their width. Again seems to be related to being initialized off screen.

Going to try to put together a more specific test case to help identify the issue.

**Comment by DataTables** [comment]
1 should already be resolved in git. For 2, yes please for a test case if not already fixed by the latest code.

**Comment by datasage** [comment]
I see the commit, will test it later tonight, or within the next couple of days.

**Comment by DataTables** [comment]
Closing this as I believe it has been resolved already. If not, please reopen with a link to a test case.

**Comment by hheimbuerger** [comment]
I had this issue with DataTables 1.10.11 (didn't occur in 1.10.9): child rows would sometimes span only the first column, instead of across the entire table. This happened by a weird pattern, specificially the issue would appear and disappear as I was changing the filtering rules of my table.

I've manually applied the changes from https://github.com/DataTables/DataTables/commit/e350e155d207ba6a02d479e0303bd33731d14a48 into my 1.10.11 sources and that fixed the issue for me. :+1:
