### ISSUE TITLE
_fnGetUniqueThs throws "Cannot read property 'aoHeader' of null"

### ISSUE THREAD

**Issue by vedmack** [DataTables/DataTables#772]
Hi,

For some reason when calling `oTable._fnGetUniqueThs();` dt throws *Cannot read property 'aoHeader' of null*, This happens when you click on the button in the upper left corner (when you try to open the dialog for the second time), please see test case: https://jsfiddle.net/7gtps9n5/15/

Any ideas why it happens?

Daniel

**Comment by vedmack** [comment]
Hi, 
Can you give me a hint / direction about that one? because I have several users asked me about this issue.

**Comment by DataTables** [comment]
In your code you have:

> unique_th = oTable._fnGetUniqueThs();

But you aren't passing in the settings object which appearst o be what is causing the issue. [This is the header](https://github.com/DataTables/DataTablesSrc/blob/master/js/core/core.draw.js#L729) for that **private** function.

**Comment by vedmack** [comment]
Thanks, I already debugged before and noticed that 1, but even after passing settings obj, it fails to work , [see updated jsbin](https://jsfiddle.net/7gtps9n5/15/) , I noticed that inside the _fnExternApiFunc (fn)

```
function _fnExternApiFunc (fn)
	{
		return function() {
			var args = [_fnSettingsFromNode( this[DataTable.ext.iApiIndex] )].concat(
				Array.prototype.slice.call(arguments)
			);
			return DataTable.ext.internal[fn].apply( this, args );
		};
	}
```

The settings eventually is passed as the second argument to the `_fnGetUniqueThs` function - instead of the nHeader argument, while the oSettings is null,  (you can place a break point in the `function _fnExternApiFunc (fn)` function to see it on my jsbin)

**Comment by DataTables** [comment]
`_fnExternApiFunc` is so that publicly added legacy API methods don't need to have the developer using the plug-in pass in the settings object. Really it should just use context, but I didn't when I first wrote that part. Live and learn...

That `_fnGetUniqueThs` is exposed on the jQuery object is absolutely a bug in DataTables (probably in the legacy support code). That most certainly should not be there.

Try using:

```js
settingsDt.oApi._fnGetUniqueThs( settingsDt );
```

However, as I say, this is a private method :-). It might "go away" in future.

**Comment by vedmack** [comment]
Awesome! 

That worked, thanks!
