### ISSUE TITLE
Uncaught TypeError: $(...).DataTable is not a function(…)

### ISSUE THREAD

**Issue by mattpepper** [DataTables/DataTables#791]
In version 1.10.**11** instantiating the DataTable throws the following error which blocks JavaScript execution: `Uncaught TypeError: $(...).DataTable is not a function(…)`

Using `$(...).DataTable({...})` to instantiate works as expected with the same code in 1.10.*x* versions up to 1.10.**9**

I have tried:both of the creation methods documented [here](http://datatables.net/upgrade/1.10), and I have checked that jQuery is loaded before the call to `$(...).DataTable({...})`is fired.

We are using jQuery version 1.12.1. 

Link to issue on hmrc/asset-frontend:
[Downgrade datatables.net version by mattpepper](https://github.com/hmrc/assets-frontend/pull/456)

**Comment by DataTables** [comment]
Can you please link to a test page showing the issue so it can be debugged.

**Comment by mattpepper** [comment]
Thanks for response - I'll get a test page together for the issue a.s.a.p. and comment here with a link.

**Comment by mattpepper** [comment]
Please find test pages at [datatables-test.mod.bz](http://datatables-test.mod.bz/).
Note that these replicate the asset deployment on our sites, with the JavaScript bundled via `browserify`. For debugging I have generated the `application.min.js` for each page **without** obsfucation or mini-fying.

**Comment by DataTables** [comment]
Thanks for the link! I think the issue is in the change that was made for the CommonJS loader in 1.10.10. You currently have:

> require('datatables');

But DataTables actually exports a function now so you would need to use:

```js
require('datatables')();
```

That should have been a major version change, and that was a mistake on my part sorry! The CommonJS aspect wasn't documented on the site which is way it wasn't a major version bump, but in retrospect that was completely wrong.

The change was required to improve the modularity of DataTables in a CommonJS environment. It now provides the ability to pass in a specific `window` and `jQuery` object. If neither are passed in, it just uses what it can find.

This interface is now documented [on the site](http://datatables.net/download/npm) and _will not change_ in a backwards incompatible way again...!

**Comment by mattpepper** [comment]
Thanks for the reply and quick turnaround in identifying the issue. 

I've updated the test pages at [datatables-test.mod.bz](http://datatables-test.mod.bz/). to show the fix is works.

**Comment by mattpepper** [comment]
Solution fixes error as expected.
