### ISSUE TITLE
scrollX option does not properly align cells in v1.10.11

### ISSUE THREAD

**Issue by jakezatecky** [DataTables/DataTables#794]
There appears to be a bug in the the `scrollX` option, as it does not appear to not be functioning properly when we do not have any horizontal overflow. When an extremely simple table is created and we enable `scrollX: true`, the header and body cells are clearly not aligned:

https://jsfiddle.net/ekv4mdw2/1/

``` html
<table>
  <thead>
    <tr>
      <th>Field 1</th>
      <th>Field 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Cell 1-1</td>
      <td>Cell 1-2</td>
    </tr>
    <tr>
      <td>Cell 2-1</td>
      <td>Cell 2-2</td>
    </tr>
  </tbody>
</table>
```

``` js
$('table').DataTable({
  scrollX: true,
});
```

When `scrollX` is disabled or not present, there is no alignment problem:

https://jsfiddle.net/xrnw8v1e/

Curiously, this was not an issue in v1.10.9 (although the same problem affects v1.10.10):

https://jsfiddle.net/4yb575kz/

**Comment by DataTables** [comment]
Hi,

The issue here is that DataTables can't see that `width:100%` in the CSS. When you get the width of an element it only gives you it in pixel terms, which is obviously virtually useless. It is possible to get it from the stylesheet, but you need to parse the CSS rules - which is horrible!

The way around this is to include `style="width:100%"` or `width="100%"` in the HTML: https://jsfiddle.net/ekv4mdw2/2/ .

Not a great solution, but the best I've been able to come up with so far.

**Comment by gregmarr** [comment]
@DataTables Thanks, that fixed my issue.
