### ISSUE TITLE
Ability to use debouncing instead of throttling

### ISSUE THREAD

**Issue by fabiospampinato** [DataTables/DataTables#809]
When using server side processing it makes more sense to use debouncing instead of throttling. Just to provide a clear example, if somebody searches, for instance,  'beautiful' I don't want my server to process a request each time for 'b','bea',  'beaut' and 'beautiful'. I could set a high `searchDelay`, let's say 1000, but it will still process 'b' and 'beautiful' at best, and at worst the user will have to wait 1000 milliseconds between requests, instead of a more reasonable 350ms or something that could be appropriate when using debouncing.

I'm basically asking for the addition of 2 new settable options:
'delayMode': 'throttle|debounce',
'serverSideDelayMode': 'throttle|debounce'

The names don't really matter. Basically `delayMode` should allow people to choose between throttling and debouncing, `serverSideDelayMode` will allow to automatically use debouncing when using server side processing.

Do you have any reason not to include this? If you agree with me I might even work on a pull request in the following days.

**Comment by DataTables** [comment]
Hi, thanks for your thoughts on this! With the next major update to DataTables I actually plan on changing the throttle to a debounce. On reflection it was the wrong option to use a throttle (I used it thinking it would make the interface feel more responsive, but its just ended up causing more issues than it was worth).

Having a `delayMode` option sounds like a nice compromise. The throttle code unfortunately can't just be removed since some of the extensions use it. I think a single `delayMode` option would be suitable.

I haven't made a branch for the next major version yet, but would be happy to pull in a PR for this when it is available (I've got a few other things to wrap up first).

**Comment by DataTables** [comment]
Going to merge this into #698 which discusses some of my ideas for the next version.

**Comment by ahmed-abdulmoniem** [comment]
Any news on that?

**Comment by Oliver-Gibson** [comment]
also interested in this feature, any news ?

**Comment by DataTables** [comment]
Not yet. It will be in the next major version when I get a chance to work on that.

**Comment by BafS** [comment]
Is there a way to implement it manually temporary ?

**Comment by DataTables** [comment]
You would need to modify the DataTables source.

**Comment by fabiospampinato** [comment]
You can sort of replace throttling with debouncing now, I do it like this:

```javascript
  $(function () {

    const $tables = $('table.datatable');

    for ( let table of $tables ) {

      const $table = $(table),
            $input = $table.find ( 'input[type="search"]' ),
            api = $table.DataTable ();

      $input.off ().on ( 'keyup cut paste', lodash.debounce ( () => api.search ( $input.val () ).draw (), api.settings ()[0].searchDelay ));

    }

  });
```

**Comment by BafS** [comment]
Thanks for your answers !

**Comment by PhilippMeissner** [comment]
Again, any news on this? Would be highly appreciated to use this natively :)
