### ISSUE TITLE
Deferred loading with multiple pages loaded at start

### ISSUE THREAD

**Issue by fabiospampinato** [DataTables/DataTables#812]
I'm currently experimenting with deferred loading and I've found a pretty limiting fact: at page load I can only output one page worth of rows, if I output more they just get added to the first page, even if the length is let's say 10 and I output 100 of them.

The point of using deferred loading is to use less server resources, if I have a table with 100k rows maybe I don't need them all at once, but since I cannot output N pages of rows at page load without asking the server for any page which is < N I'm actually using many more server resources in this, I believe, pretty common use case:

Let's say there's a website that provides each of their registered users with a table for managing images they uploaded, the vast majority of the users will have a pretty limited amount of uploads, in this case it will be better to ask the server for data just once, hence outputting the first N pages worth of results. But it's not possible to always output all results because in few limited cases some users uploaded a considerable number of images. Basically if we enable deferred loading we get way to many requests to the server, if we output all results the page will take forever to load, if not crash, for a few users. An hybrid approach is needed.

I suggest it to be working this way: if the length per page is set to 10 and I output 50 results than only the first 10 of them will be showed in the first page. We already have the data for showing pages 2, 3, 4 and 5 so we'll not ask the server. If a custom ordering or a search occur and we don't already have all the rows we'll send a request to the server.

This will unlock another pretty powerful feature: if the total numbers of rows is equal to the rows we are outputting at page load we don't even need to contact the server at all, not even for searching or ordering.

Of course one could choose to use deferred loading or not on the basis of how many rows there are, but it will be nice to have this integrated into DataTables.

**Comment by DataTables** [comment]
You can use [pipelining as shown in this example](https://datatables.net/examples/server_side/pipeline.html) if you want to load more rows that required.

In future, please post future support requests in the [DataTables forums](//datatables.net/forums). I'm trying to built it up to be a searchable resource for DataTables information instead of having it split between here and there.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, but I'd like to point out that the point of my reasoning was to not make any ajax call after page load if we already displayed the results, not asking the server again for those N pages and then caching them.

In which way 128 lines of custom code and an ajax call is better than just using the rows we already have? Btw I would argue that outputting a few pages worth or results just means changing a number in the LIMIT portion of a SQL query, which is undoubtedly easier then 128 lines of javascript.

If you're still not convinced this is an issue worth fixing I'd like to also highlight that reading `Showing 1 to 10 of 1000 entries` when there are 50 entries displayed doesn't like quite right.

**Comment by DataTables** [comment]
> Showing 1 to 10 of 1000 entries when there are 50 entries displayed doesn't look quite right.

Can you give me a link to a page showing issue please.

**Comment by fabiospampinato** [comment]
Sure, [here](http://live.datatables.net/kidanone/1/edit) you go.

**Comment by DataTables** [comment]
Thanks.

I would actually consider that a misconfiguration. If you display 50 rows in the HTML you should set the page length to be 50 in initialisation.

Yes DataTables could possibly detect that automatically, so it could be considered a bug, but at the moment I think its a misconfiguration.

**Comment by fabiospampinato** [comment]
Ok, in case you'll ever consider that a great way of saving 128 lines of javascript, an ajax call and the fix of an issue let me know.

**Comment by DataTables** [comment]
One of the reasons I don't want to include it in the core is that it is just moving the 128 lines of Javascript into the core library, so people who don't want it will need those extra 128 lines. Indeed, server-side processing is used only in the minority of use cases, so this would just be dead code for the most part.

As such, I believe this should live in a plug-in which can be assigned to the `ajax` parameter.

**Comment by fabiospampinato** [comment]
I think I've said everything I had to, but really, why don't you remove server side processing support all together then? Because If somebody uses it in a non trivial way and he/she is not stupid I don't see any reason why he/she would like to waste time in, at best, an ajax request... without considering the amount of time needed just to understand how that pipelining thing works.

I have the feeling that either I'm seeing too much value in issues like this and #811 or you have never used DT in big enough ajax-backed tables. Having been using search throttling for years instead of debouncing drives me towards the latter, but don't get me wrong, for the most part I appreciate all the work that has been done.

**Comment by DataTables** [comment]
I think providing support for server-side processing would be quite difficult to do as a plug-in since the core has be be aware of the fact that it only has a subset of the rows that are actually available (which is not the case when client-side processing).

Having said that, the goal is to have DataTables more modular so you could make a build without server-side processing if you don' want it.

With regarding to pipelining specifically, in my experience when working with millions of rows of data, you typically want to use filtering and sorting more often than paging and for those actions any client-side cache is immediately invalidated. It absolutely can be useful to help speed up paging and reduce requests to servers, but I don't think it is a fundamental feature needed for server-side processing.

I will however try to get the pipeling code into its own plug-in and include it on the CDN alongside the 1.10.12 release.
