### ISSUE TITLE
colvis buttons issue with dynamically adding more buttons

### ISSUE THREAD

**Issue by 719media** [DataTables/DataTables#813]
I noticed when dynamically adding more buttons to datatables that the colvis active setting throws an error.

This can be seen in the following fiddle:

https://jsfiddle.net/719media/t2vaj88t/3/

click on the columns and notice that the active state does not get changed (and js error thrown). If you remove the dynamic add column, things work normally.

It has something to do with the column index referencing, as dynamically adding more buttons AFTER the buttons/colvis instance does not trigger the issue, only if adding it before (and therefore changing the colvis index).

**Comment by DataTables** [comment]
Thanks for this. It should probably be filed at DataTables/Buttons or in the forums, however this is a bug for sure. And unfortunately its a bit of a rabbit warren bug - the deeper you go the bigger it gets...

The basic issue here is that the reference that the event handler is using for a button is out of date after adding a new button (it uses an array index). Since the `init` function is using a closure, that out of date reference is used.

I could just have the code get a new reference to the button since the node is being passed in, but the nodes can be regenerated when adding buttons, so actually the node reference is also out of date. This is resulting in a memory leak when you add a new button dynamically...

So it needs:

* To reuse already constructed buttons when a new button is added
* Change the internal referencing to use nodes rather than indexes

I was planning to do a 1.2 release of Buttons this week, so it makes sense to put a large change like this into it, although it might push the release back into next week...

Thanks for flagging it up. I'll post back when I've made the required changes.

**Comment by DataTables** [comment]
That was a bit of an epic :-). [Fixed in Buttons](https://github.com/DataTables/Buttons/commit/bc91ec3884f69f342b5cb3e71e8feab61faaa08f) and will be included in the 1.2.0 release.

**Comment by 719media** [comment]
Wow that was fast. Thanks! You're awesome!
