### ISSUE TITLE
Issue with Renaming Excel Export in IE/Edge

### ISSUE THREAD

**Issue by bamblack** [DataTables/DataTables#814]
I'm currently running in to an issue with exporting data to Excel using the Buttons plugin in Internet Explorer. It's being caused by the limited options in the `Save as type` dropdown. When I attempt to export it, the default file name is the title of the page I'm on plus .xlsx; if I change nothing and just hit Save, it works. However, if I attempt to rename the file I have to manually add the extension because the `Save as type` is **All Files (.)** and there are no other options. So if a user who doesn't realize they have to add the file extension does this, it saves it as a plain File instead of a worksheet.

Compare this to Chrome that works perfectly because the `Save as type` is **Microsoft Excel Worksheet**, so it doesn't need the file extension added. Is this something that can be fixed in the code or is it a limitation of the browser?

**Comment by DataTables** [comment]
Apologies if the request in the github new issue template and the contributing document aren't clear enough. Could you post support requests in the [DataTables forums](//datatables.net/forums) please, so that there is a single searchable point for support requests.

When you post in the forum could you link to a page showing the issue, even if that is on the DataTables' site (so I know the configuration being used). Also, if you could post a link to your question in the forum here, so if anyone does happen to find this one they know where to go.

Thanks,
Allan

**Comment by bamblack** [comment]
Sorry about that, I've asked the question here: https://datatables.net/forums/discussion/34820/issue-with-renaming-excel-export-in-ie-edge?new=1
