### ISSUE TITLE
The DataTables' event order picture

### ISSUE THREAD

**Issue by ssy341** [DataTables/DataTables#817]
Hi,
@DataTables, Do you have the DataTables' event order picture? I need it to figure out inner how to do. Would you do me a favour? Thank you all the same.

**Comment by DataTables** [comment]
Do you mean a list of the order of the events? No - sorry that is not something I have. You could listen listen code all events and then `console.log` the event name since the order depends upon your configuration.

In future, could you post support requests in the [DataTables forums](//datatables.net/forums) as requested in the GitHub new issue text and also the Contributing document.
