### ISSUE TITLE
When use the autoWidth with column width options simultaneously, it cause a problem

### ISSUE THREAD

**Issue by stegano** [DataTables/DataTables#821]
When use the autoWidth with column width options simultaneously, column width is not work.

Solution: if use autoWidth value is false and use column width option then should apply to CSS(table-layout: fixed to Table tag) 

Thank you :D

**Comment by DataTables** [comment]
In this example it appears to work as expected: http://live.datatables.net/pumimaye/1/edit . Note that the first column has 30% width applied to it and if you use your browser's inspector tools you will see that column has 30% width applied to it in the DOM. It doesn't take up 30% width of course, since it can't (the browser's table layout method will optimise the layout based on the content and the width applied - that is an expected part of using tables in the browser).

If this is still an issue, please open a new thread in the [DataTables forums](//datatables.net/forums) as requested in the "New Issue" text and also the contributing document, with a link to a test page showing the issue.

**Comment by stegano** [comment]
@DataTables 

Thanks for your reply. 

But i didn't solution :(, please check the url - https://jsfiddle.net/uyxydn7v/
(e.g. I want to make all columns to be width 300pixel)

Thank you :D

**Comment by DataTables** [comment]
As requested, please open a thread in the DataTables forums with a link to the test case and I will reply there. If you could paste the link here when you do I will take a look.

**Comment by stegano** [comment]
@DataTables 
I wrote issue from Datatables forums :D wait for a answer.

**Comment by DataTables** [comment]
Could you link to it as I asked above please? There are 40+ new threads a day in the forum and its easy to loose track of them.

**Comment by stegano** [comment]
@DataTables 
Please check the link :D
- https://www.datatables.net/forums/discussion/35163/when-use-the-autowidth-with-column-width-options-simultaneously-it-cause-a-problem#latest

Thank you :)
