### ISSUE TITLE
Column width wrong

### ISSUE THREAD

**Issue by brandonros** [DataTables/DataTables#822]
![image](https://cloud.githubusercontent.com/assets/8949910/15403224/faaa1426-1dc5-11e6-8532-4ffd42b02ddb.png)

```
$('#inventory_alerts').DataTable().columns.adjust().draw();
$(window).trigger('resize');
```

Both have no effect.

Before this table is loaded, it's hidden. Could that have to do with it? This happens all throughout my app.

**Comment by brandonros** [comment]
![image](https://cloud.githubusercontent.com/assets/8949910/15403273/234cb8de-1dc6-11e6-9493-ddb75c8e80ce.png)

Please let me know what other information I can provide.

**Comment by DataTables** [comment]
Apologies if the information in the "New issue" text and the Contributing document are not clear enough. Please do not post support requests here - post them in the [DataTables forums](//datatables.net/forums). As requested here, and also in the forums, please link to a test case showing the issue when you do.

As noted in the "new issue" text, support requests here will be closed.

**Comment by brandonros** [comment]
How is this a support issue?... This is a bug, no?

**Comment by DataTables** [comment]
Without a test case it is impossible to say for certain, but I think it is very likely to be the same issue as demonstrated in [this example](https://datatables.net/examples/api/tabs_and_scrolling.html) (albeit without tabs perhaps, but the same principle).

If you simply search the DataTables forums for "table width hidden" you would find [a](https://datatables.net/forums/discussion/3796/incorrect-table-width-in-hidden-containers) [lot](https://datatables.net/forums/discussion/12228/how-do-i-increase-table-width-when-dynamically-showing-hidden-columns) [of](https://datatables.net/forums/discussion/23334/fixedheader-misaligned-when-table-is-hidden-at-start-and-incorrect-width-when-resizing-page) [threads](https://datatables.net/forums/discussion/26284/scrollx-causes-style-issues-when-hidden-table-container-becomes-visible) [on](https://datatables.net/forums/discussion/16492/header-not-resized-properly-on-init-from-hidden-div) [the](https://datatables.net/forums/discussion/16548/header-corrupted-when-plugin-was-applied-for-hidden-div) [topic](https://datatables.net/forums/discussion/24316/table-header-misaligned-with-vertical-scroll-when-display-none).

The site search isn't brilliant - I'll be replacing it soon, but it would help here I think. This is one of the reasons that all support requests (and bug reports) should go to the forums - so they can be searchable in a single location. I'm considering disabling issues in this repo when the new site search is online since support requests still come through here despite requests for them not to.

**Comment by brandonros** [comment]
> Without a test case it is impossible to say for certain, but I think it is very likely to be the same issue as demonstrated in this example (albeit without tabs perhaps, but the same principle).

> $('#inventory_alerts').DataTable().columns.adjust().draw(); has no effect.

> https://datatables.net/forums/discussion/3796/incorrect-table-width-in-hidden-containers

2014, old style API.

> https://datatables.net/forums/discussion/23334/fixedheader-misaligned-when-table-is-hidden-at-start-and-incorrect-width-when-resizing-page

Homie never got a response back from 2014.

What is the new method for `fnAdjustColumnSizing`?

**Comment by DataTables** [comment]
`columns.adjust()` is the new method as noted in [the conversion guide](https://datatables.net/upgrade/1.10-convert).

If that isn't working I would need a link to a test case showing the issue to understand why not. That is why the Contributing document and template text both ask for one, why it is required in the forum and why my first and second replies here ask for one.

**Comment by IRoye** [comment]
@brandonros   thx , your  solution (" $('#inventory_alerts').DataTable().columns.adjust().draw(); ") resolved my problem , its works in my code
