### ISSUE TITLE
Sorting doesn't work in some case

### ISSUE THREAD

**Issue by JisaKun** [DataTables/DataTables#844]
Here's the demo: http://codepen.io/JisaKun/pen/mPZJmB

The initial state is sorting by column `Name` desc , When you keep clicking the header of column `Name` to sort as soon as the table was initialized, sorting only works one time.But it works well if you sorting table by another column at first.

Do I make my self clear ?

**Comment by DataTables** [comment]
Very clear. However, I guess I wasn't clear in the Contributing document or the template text that GitHub displayed in new issues. Support issues should be reported in the [DataTables forums](//datatables.net/forums).

I think the issue here is that you are giving the order index as a string - it should be an integer - e.g. `order:[1, 'desc']` (not `'1``).
