### ISSUE TITLE
Datatables is removing classes from hidden rows and cells. 

### ISSUE THREAD

**Issue by Jaded-Design** [DataTables/DataTables#864]
We have classes assigned to certain td's so that we can manipulate them as the user interacts with our application. Unfortunately it looks like Datatables is stripping out the classes from the rows and cells that are being hidden (for responsive mode).

I tried to use a Datatable Render from here: 
https://datatables.net/reference/option/responsive.details.renderer

But that doesn't seem to allow me to maintain the td classes, only replace them with "default" classes. 

This seems like a really bad way to handle rendering hidden rows. I guess I don't understand why you wouldn't just keep the existing classes and add the childelement class. 

Am I just missing something? Is there a way to keep the classes?

**Comment by DataTables** [comment]
Apologies if the "New issue" template text isn't clear. Could you post question in the [DataTables forums](//datatables.net/forums) please, with a link to a test case showing the issue.

From what I understand here, you have a cell with class names applied to it, but are wondering why that class name is not used in the responsive view. Is that correct? If so, that is because the responsive view doesn't use the `td` cell from the DataTable - by default it uses a `ul/li` list and a copy of the data. There is currently no option to have Responsive use the original cell from the table (I did try that before, but found it introduced a lot of complexity and resolved to go back to it when I had time to do so).

**Comment by Jaded-Design** [comment]
You are correct about the situation. 

Instead of using the original cell would it be possible to just capture the current classes, id, and data-* and pass them into the newly rendered ul/li? 

I did find a minor workaround in that I can use the details.renderer to push the title of the column into the class of the cell. Not ideal but it's a work around. 

I think this feature would make a lot of sense.

**Comment by DataTables** [comment]
Copying classes sounds like a good idea to allow styling to be maintained - thanks for the suggestion. I've opened an issue for this in the Responsive repo.

I'm less keen on copying the ID - the way Responsive works is to hide the cells with `display:none`, so the cells are still present in the DOM, with their id. Copying the id to another element would mean that there were two elements with the same id, which isn't valid.

**Comment by Jaded-Design** [comment]
Can I also suggest that you allow the classes to be pushed into the details.renderer so that not only can you still capture the original class but you could also custom render the hidden areas and put back that class. So in our situation we found that we could better control the alignment and layout by using the renderer to render the spans as td's. In our situation I'd love to be able to insert a col.classes into the td element. 

I think this minor change could really help open up more interactions inside of the datatables hidden rows.
