### ISSUE TITLE
Problems with 1.10.13 and Requirejs

### ISSUE THREAD

**Issue by rommsen** [DataTables/DataTables#894]
Hi there,

sorry in advance. I know that this might be the most vague bug report ever but I do not know where to start.

We are building our JS with requirejs and since updating to 1.10.13 the tables wont show up anymore after the build process (concatenation, minifying). There is no error in the console, nothing, the tables just wont render. They make an ajax request but the table is not rendered with the results. This problem does *not* occur when we use the library without the build process (so the datatable JS is requested separately). When downgrading to 1.10.12 everything works as expected. Are there any differences between 1.10.12 and 1.10.13 that will explain this behavior?

Regards

**Comment by DataTables** [comment]
Not that I'm aware of. I would need a link to a test page showing the issue to be able to help debug it.

**Comment by rommsen** [comment]
Thanks for the quick reply. I prepared test systems: if you dont mind logging in:

User: datatables@datatables.net
PW: datatables

Working 1.10.12: https://agentur.promosoftware.de/project/list
Not Working 1.10.13:  https://agentur.staging.promosoftware.de/project/list

The concatenated files are in bootstrap.js. I disabled minification.

**Comment by DataTables** [comment]
Its being caused by this:

```js
                // wenn Tabelle nicht mit den gespeicherten Daten geladen werden soll,
                // oder noch keine Werte vorhanden sind
                if (self._tableOptions.clearSavedState || loaded === undefined) {
                    self._filterCtrl.setFilterValues({}, self._tableOptions.default_filter);
                    return;
                }
```

That return gives `undefined` back to the state loader, which in 1.10.13 is telling it to wait for the async callback to be triggered. That never happens in this code.

To fix just use `return {};`.

This was changed in 1.10.13 to allow the state loading function to perform an async action (i.e. get data from a remote database) and then execute the callback when done. There needed to be a way of "telling" the function that the callback would be used, so I assumed (apparently incorrectly) that the state loading function would always return an object, unless it was going to perform an async action.

So not a bug I'm afraid, but rather an unintentional backwards incompatibility with something that wasn't documented.

**Comment by rommsen** [comment]
It works. Awesome! Thank you so much for this quick solution. I have no clue how you managed to dig into this that fast and I am deeply impressed. Hats off :+1:
