### ISSUE TITLE
Check all checkbox in datatable server side processing

### ISSUE THREAD

**Issue by timyounes** [DataTables/DataTables#899]
It is possible to check all checkbox in all pages in the datatable server side processing result?

**Comment by morrow95** [comment]
I needed this same functionality with server side and I ended up just leaving it check all values on that particular page (what is shown at the time).  The problem is you are only returning a subset of values on any given page and not the entire result set.  Unless you are loading every single result on the viewable page (no pagination) you will never be able to retrieve all 'id' values of the result set from datatables.

In my case I wanted to give an option to 'delete all' so I just made a button specific for that.  When it is clicked and the user confirms that is what they want to do I have my own code delete the entire result set with a delete query to the database.

**Comment by timyounes** [comment]
Do you have sample code using jquery or javascript?

**Comment by morrow95** [comment]
You would just do an on click handle for your button and then process the delete through ajax... I am doing something like : 

```
$('#delete-all').on('click', function () {

    // values you want to send to your script through ajax
    var data = {
      	'type': 'file'
    };
			
    $.ajax({
        type: 'post',
        url: '/delete.php',
        data: data,
        dataType : 'json'
    }).done(function (response) {
    
    ... and so on to handle responses

```

**Comment by DataTables** [comment]
You could use the [`draw` event](https://datatables.net/reference/event/draw) to know when the table has been redrawn and select the checkboxes.

As morrow95 points out, you are only selecting the rows on the client-side, so a "select all" would only select those that exist at the client-side, which could be confusing, depending on what you want to do.

In future, could you please post support questions in the [DataTables forums](//datatables.net/forums) as requested in the template text and contributing document. Thanks.

**Comment by timyounes** [comment]
https://datatables.net/forums/discussion/39784/check-all-checkbox-in-datatable-server-side-processing

**Comment by timyounes** [comment]
Thanks guys.. !
I got the solution in your comments. 
I use [draw event](https://datatables.net/reference/event/draw) to know when the table has been redrawn and check the header checkbox if it is checked, if it is checked then do the command to checked all the checkbox in the table and pass the row id to array variable or you can use hidden textbox.
