### ISSUE TITLE
Inline creates a new column and column does it inline (repro added - jsBin)

### ISSUE THREAD

**Issue by Legends** [DataTables/DataTables#909]
As stated [here --> responsive.details.type](https://datatables.net/reference/option/responsive.details.type) 

> inline - where the first column in the table has additional padding added to it and the :before pseudo element is used to display the button.

and column:

> column - where a whole column is dedicated to the show / hide control.

In my case **inline** creates a new column for the button. And "**column**" does what "inline" should do!!!

[jsBin reproduction](http://jsbin.com/dezuga/edit?html,js,output)
Here is a repro: jsbin.com/dezuga/edit?html,js,output

As you can see,... column does it inline...

**Comment by DataTables** [comment]
Hi,

We [discussed this a bit in the forum](https://www.datatables.net/forums/discussion/40456/complex-headers-plus-sign-not-in-separate-column-solved#latest). I think basically the issue here is just that when using a "column" type, it expects there to be nothing in the column, so a new column needs to be added.

Example: http://jsbin.com/yanugatopa/edit?html,js,output
