### ISSUE TITLE
Content is rendered as HTML

### ISSUE THREAD

**Issue by JorisWillekens** [DataTables/DataTables#916]
Hello

I have a problem with rendering data. 
The first column contains a product ID, these are unnecessarily converted to HTML.

Example
D&LT123 is converted to D<123.

I fixed this in fnRowCallback, so the data displayed is correct, but when I search for D&LT, no results are found, if I search for D<123, I get results.

**Comment by DataTables** [comment]
Hi,

DataTables will write content to the `.innerHTML` of the cells, so yes, any HTML elements would be shown converted as such.

If you don't want that to happen, you could either:

1. Use the [built in `text` renderer](https://datatables.net/manual/data/renderers#Text-helper)
2. Encode your HTML entities (e.g. `&amp;` rather than `&`)

In future, could you post support requests in the [forums](//datatables.net/forums) as requested in the new issue template text please?
