### ISSUE TITLE
Nested object with null parent

### ISSUE THREAD

**Issue by Seb33300** [DataTables/DataTables#919]
When data source is [nested object](https://datatables.net/examples/ajax/deep.html), if one of the object which should have children is null, this result in an error:

> DataTables warning: table id=sg-datatables-xxx - Requested unknown parameter 'user.name' for row 0, column 1. For more information about this error, please see http://datatables.net/tn/4

When expected data is:
```json
{
    "user": {
        "name": "XXX",
        "email": "XXX@XXX.com"
    }
}
```
But received data is:
```json
{
    "user": null
}
```

If user is null, children property should be considered as null too, and don't throw an error.

Seb

**Comment by DataTables** [comment]
Hi - I'm afraid that I disagree with the premise that it should treat it as null based on the fact that in Javascript null !== undefined.

What I would suggest instead is that you make use of the [columns.defaultContent option](https://datatables.net/reference/option/columns.defaultContent) which will be used instead of an undefined value if it is found to be undefined.

In future, could you post support requests in the forums, as required in the new issue template text rather than here. Thanks!
