### ISSUE TITLE
_fnCallbackFire with 'error' event calls window.onerror with wrong arguments

### ISSUE THREAD

**Issue by serdyuk-alex** [DataTables/DataTables#937]
Here is line which does it wrong way:

```_fnCallbackFire( settings, null, 'error', [ settings, tn, msg ] );```

Arguments should be provided according to window.onerror signature:
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by DataTables** [comment]
This triggers an `error.dt` event (i.e. a jQuery event namespaced with .dt). It an "controlled" error that is specific to DataTables rather than a Javascript error (although one can perhaps lead to the other).

I don't think triggering a global error would be quite the right thing to do here since I don't have all of the information that the global onError needs.

Perhaps the main issue is that I shouldn't have called it `error`, but instead something more specific to DataTables. But I felt the namespacing should deal with that?
