### ISSUE TITLE
search.dt is triggered on ordering

### ISSUE THREAD

**Issue by davidkonrad** [DataTables/DataTables#953]
The `search.dt` event is triggered also when the user is ordering, i.e is clicking on a table header. I think this may be a little blunder because there also is the overlapping `order.dt` event. It is not logical having two different events that both is triggered on the same action. Furthermore, talking in logic terms, there is no search performed when ordering. Reference for the issue -> https://stackoverflow.com/q/45037459/1407478

**Comment by DataTables** [comment]
Actually, this is technically correct as DataTables does do a filter when sorting is applied to the table.

[This is the line of code that triggers that](https://github.com/DataTables/DataTablesSrc/blob/11ed3b0065e0dbdd5dc9e206a1867df2efef4ac8/js/core/core.sort.js#L322). The `_fnReDraw` function will trigger both order and search.

The reason it is done this way is that the order is applied to the entire data set, and then rather than also applying the sort to the filtered data set, it applies the filter again. It would need to be one or the other - neither optimal perhaps, but this is the way I've chosen to implement it.
