### ISSUE TITLE
npm package with minified version

### ISSUE THREAD

**Issue by erichstark** [DataTables/DataTables#969]
It is possible to provide minified version of datatables as part of npm package?

**Comment by DataTables** [comment]
Yes - use `datatables.net` - see the [NPM section of the manual](//datatables.net/download/npm).

**Comment by erichstark** [comment]
I have tried it before opening this issue.
After installing package 
npm install datatables.net
there is only one source file.

**Comment by DataTables** [comment]
[This is the repo for that package](https://github.com/DataTables/Dist-DataTables/tree/master/js) - it contains both the min file and the non-min file.

**Comment by erichstark** [comment]
@DataTables thank you for the tip! But I think, it is just easier to have dist folder in one package like jquery does.

**Comment by DataTables** [comment]
The reason that doesn't really work for DataTables is due to its support for the various styling frameworks such as Bootstrap, Bootstrap 4, Semantic UI, etc. Simply bundling all of those files together into a `dist` directory would mean you always have to specify the path in the `require` statement. That's possible, but I think its easier to do `require( 'datatables.net-bs' );`.
