### ISSUE TITLE
'Sort' option does not keep table id

### ISSUE THREAD

**Issue by JoshuaKlassen** [DataTables/DataTables#988]
Currently I am using css to style a particular datatable, and it relies on the table having an `id` so that it can apply the styling.
When the table does not have the `scrollY` set, this works as expected.
However, when I enable this feature (like: `scrollY: 100`), the `id` is lost on the table (according to the Chrome dev tools) and none of the styles get applied.

for example:
```
<table id="myTable">
...
</table>

...


#myTable thead {
    background-color: red; /* just to see the styles are getting applied */
}
```

without scrollY the styles get applied:
```
$('#myTable').DataTable({
    paging: false,
    columns: ...
});
```

however with scrollY the style is ignored because the `id` on the `table` element is gone:
```
$('#myTable').DataTable({
    scrollY: 100,
    paging: false,
    columns: ...
});
```

I am wondering if this is a bug or is it intended?

If you are needing any more information please let me know

Thanks,

Josh

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

> however with scrollY the style is ignored because the id on the table element is gone:

The table gets split into two or three parts (depending if there is a footer) when scrolling is enabled. The body part gets the id (since there can't be multiple elements with the same id). 

See [this thread](https://datatables.net//forums/discussion/comment/112358/#Comment_112358) among others on the same topic.

**Comment by JoshuaKlassen** [comment]
My apologies.
I appreciate your response, that clears things up a lot!
